#!/bin/sh

USER="hduser"
CMD="/usr/local/oozie/bin/oozied.sh"
SERVICE=`basename $0`
PID="/var/run/$SERVICE.pid"
LOG="/var/log/$SERVICE.log"

case "$1" in
    start)
	    if [ -f "$PID" ] && ps `cat "$PID" > /dev/null 2>&1` > /dev/null 2>&1; then
	    	echo "Service already running"
	  	else
	    	echo "Starting $SERVICE..."
	    	sudo -u "$USER" $CMD $1 >> "$LOG" 
	    	echo $! > "$PID"
	    	if ! [ -f "$PID" ] && ps `cat "$PID"` > /dev/null 2>&1; then
	    	  echo "Something went wrong, see $LOG"
	      	  return 1
	    	fi
	  	fi
        ;;
    stop)
		if ! [ -f "$PID" ] && ps `cat "$PID" > /dev/null 2>&1` > /dev/null 2>&1; then
	        echo "Service not running"
	        return 1
		fi
	    echo "Stopping $SERVICE..."
	    sudo -u "$USER" $CMD $1 >> "$LOG" 
	    echo "Service Stopped"
	    rm -f "$PID"
        ;;
    restart)
        echo "Restarting $SERVICE..."
	    sudo -u "$USER" $CMD stop >> "$LOG"
	    rm -f "$PID"
	    sudo -u "$USER" $CMD start >> "$LOG"
	    echo $! > "$PID"
esac

exit 0