#!/bin/sh

USER="hduser"
CMD_1="cd /usr/local/flume"
CMD_2="bin/flume-ng agent bin/flume-ng agent --conf ./conf/ -f conf/flume.conf -n agent > /dev/null 2>&1"
SERVICE=`basename $0`
PID="/var/run/$SERVICE.pid"
LOG="/var/log/$SERVICE.log"

start() {
  if [ -f "$PID" ] && ps `cat "$PID" > /dev/null 2>&1` > /dev/null 2>&1; then
      echo "Service already running"
    else
      echo "Starting $SERVICE..."
      $CMD_1;sudo -u "$USER" $CMD_2 &
      echo $! > "$PID"
      if ! [ -f "$PID" ] && ps `cat "$PID"` > /dev/null 2>&1; then
        echo "Something went wrong"
          return 1
      fi
    fi
}

stop() {
  if ! [ -f "$PID" ] && ps `cat "$PID" > /dev/null 2>&1` > /dev/null 2>&1; then
        echo "Service not running"
        return 1
  fi
    echo "Stopping $SERVICE..."
    kill `cat $PID`
    echo "Service Stopped"
    rm -f "$PID"
}

case "$1" in
    start)
      start
      ;;
    stop)
      stop
      ;;
    restart)
      stop
      start
      ;;
esac

exit 0