INSERT INTO backend_orkaimage VALUES (1, 'Hadoop-2.5.2', '3f1f5195-7769-44ba-a4c2-418d86e30f97', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"Hadoop":{"version":"2.5.2","help":"https://hadoop.apache.org/"},"Flume":{"version":"1.6","help":"https://flume.apache.org/"}}');
INSERT INTO backend_orkaimage VALUES (2, 'Cloudera-CDH-5.4.4', '05f23bb1-5415-4da3-8e8a-93daa384b2f8', '{"Debian":{"version":"7.8","help":"https://www.debian.org/"},"Hadoop":{"version":"2.6.0-cdh5.4.4","help":"https://hadoop.apache.org/"},"Flume":{"version":"1.5.0-cdh5.4.4","help":"https://flume.apache.org/"},"Hue":{"version":"3.7.0","help":"http://gethue.com/"},"Pig":{"version":"0.12.0-cdh5.4.4","help":"http://pig.apache.org/"},"Hive":{"version":"1.1.0+cdh5.4.4","help":"http://hive.apache.org/"},"Hbase":{"version":"1.0.0-cdh5.4.4","help":"http://hbase.apache.org/"},"Oozie":{"version":"4.1.0-cdh5.4.4","help":"http://oozie.apache.org/"},"Spark":{"version":"1.3.0","help":"http://spark.apache.org/"},"Cloudera":{"version":"5.4.4","help":"http://www.cloudera.com/content/cloudera/en/home.html"}}');
INSERT INTO backend_orkaimage VALUES (3, 'Hue-3.8.0', '7a8423da-0cfb-414c-9491-1dcb81a87eb6', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"Hadoop":{"version":"2.5.2","help":"https://hadoop.apache.org/"},"Flume":{"version":"1.6","help":"https://flume.apache.org/"},"Hue":{"version":"3.8.0","help":"http://gethue.com/"}}');
INSERT INTO backend_orkaimage VALUES (4, 'Ecosystem-on-Hue-3.8.0', 'dc171a3d-09bf-469d-9b7a-d3fb5c0afebc', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"Hadoop":{"version":"2.5.2","help":"https://hadoop.apache.org/"},"Flume":{"version":"1.6","help":"https://flume.apache.org/"},"Hue":{"version":"3.8.0","help":"http://gethue.com/"},"Pig":{"version":"0.15.0","help":"http://pig.apache.org/"},"Hive":{"version":"1.2.0","help":"http://hive.apache.org/"},"Hbase":{"version":"1.0.1.1","help":"http://hbase.apache.org/"},"Oozie":{"version":"4.1.0","help":"http://oozie.apache.org/"},"Spark":{"version":"1.3.1","help":"http://spark.apache.org/"}}');
INSERT INTO backend_orkaimage VALUES (5, 'Debian Base', 'd3782488-1b6d-479d-8b9b-363494064c52', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"Hadoop":{"version":"2.5.2","help":"https://hadoop.apache.org/"}}');
INSERT INTO backend_orkaimage VALUES (6, 'Hadoop-2.7.1', 'f73644bb-b51c-4a27-90c7-9a4374ffe362', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"Hadoop":{"version":"2.7.1","help":"https://hadoop.apache.org/"},"Flume":{"version":"1.6","help":"https://flume.apache.org/"}}');

INSERT INTO backend_vreimage VALUES (1, 'Drupal-7.37', 'd6593183-39c7-4f64-98fe-e74c49ea00b1', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"Drupal":{"version":"7.37","help":"https://www.drupal.org/drupal-7.0"},"Docker":{"version":"1.6.2","help":"https://docs.docker.com/"},"MySQL":{"version":"5.6.25","help":"http://dev.mysql.com/doc/"}}');
INSERT INTO backend_vreimage VALUES (2, 'Redmine-3.0.4', 'f64a11dc-97bd-44cb-a502-6c141cc42bfa', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"Redmine":{"version":"3.04","help":"https://www.redmine.org/"},"Docker":{"version":"1.6.2","help":"https://docs.docker.com/"},"PostgreSQL":{"version":"9.4","help":"http://www.postgresql.org/"}}');
INSERT INTO backend_vreimage VALUES (3, 'Mediawiki-1.2.4', 'b1ae3738-b7b3-429e-abef-2fa475f30f0b', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"MediaWiki":{"version":"1.24","help":"https://www.mediawiki.org/wiki/MediaWiki"},"Docker":{"version":"1.6.2","help":"https://docs.docker.com/"},"MySQL":{"version":"5.6.25","help":"http://dev.mysql.com/doc/"},"PHP":{"version":"5.6","help":"https://php.net/"}}');
INSERT INTO backend_vreimage VALUES (4, 'DSpace-5.3', '6a6676d4-213c-464b-a321-04998c1d8dc7', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"DSpace":{"version":"5.3","help":"http://www.dspace.org/introducing"},"Docker":{"version":"1.6.2","help":"https://docs.docker.com/"},"PostgreSQL":{"version":"9.4","help":"http://www.postgresql.org/"},"Maven":{"version":"3.2.1","help":"https://maven.apache.org/"},"Ant":{"version":"1.9.4","help":"http://ant.apache.org/"},"Tomcat":{"version":"8.0.9","help":"http://tomcat.apache.org/"}}');
INSERT INTO backend_vreimage VALUES (5, 'BigBlueButton-0.81', '0d26fd55-31a4-46b3-955d-d94ecf04a323', '{"Debian":{"version":"8.0","help":"https://www.debian.org/"},"BigBlueButton":{"version":"0.81","help":"http://docs.bigbluebutton.org/"},"Docker":{"version":"1.6.2","help":"https://docs.docker.com/"}, "Tomcat":{"version":"6.0.24","help":"http://tomcat.apache.org/"}}');

INSERT INTO backend_publicnewsitem VALUES (1, '2015-06-29 15:35:24+03', 'Flume installed on all existing pre-cooked Hadoop images', NULL);
INSERT INTO backend_publicnewsitem VALUES (2, '2015-06-15 15:35:31+03', 'Ecosystem, Hue, Cloudera images available', NULL);
